[
  {
    "project": "Chia-Network/chia-blockchain",
    "commit": "373fd13ed6bdfe3f23ec733821a3eeffafde8d8d",
    "filename": "src/server/server.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/Chia-Network-chia-blockchain/src/server/server.py",
    "file_hunks_size": 11,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "src/server/server.py:285:42 Call error [29]: `Optional[typing.Callable[..., typing.Any]]` is not a function.",
    "message": " `Optional[typing.Callable[..., typing.Any]]` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 285,
    "warning_line": "            async for outbound_message in self._on_connect_generic_callback():"
  }
]