[
  {
    "project": "plone/Products.CMFPlone",
    "commit": "01dab6e6d4eecf56f0e5b8739bf9255015517395",
    "filename": "Products/CMFPlone/skins/plone_prefs/prefs_error_log_setProperties.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/plone-Products.CMFPlone/Products/CMFPlone/skins/plone_prefs/prefs_error_log_setProperties.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "Products/CMFPlone/skins/plone_prefs/prefs_error_log_setProperties.py:14:60 Unbound name [10]: Name `ignored_exceptions` is used but not defined in the current scope.",
    "message": " Name `ignored_exceptions` is used but not defined in the current scope.",
    "rule_id": "Unbound name [10]",
    "warning_line_no": 14,
    "warning_line": "context.error_log.setProperties(keep_entries, copy_to_zlog, ignored_exceptions)"
  }
]