[
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "benchmarks/100_million_downloads/client-pypeln-io.py",
    "min_patch_found": false,
    "full_warning_msg": "benchmarks/100_million_downloads/client-pypeln-io.py:20:4 Incompatible parameter type [6]: Expected `pl.task.stage.Stage` for 2nd positional only parameter to call `pl.task.api.each` but got `typing.Generator[str, None, None]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "examples/process_error.py",
    "min_patch_found": false,
    "full_warning_msg": "examples/process_error.py:17:0 Incompatible variable type [9]: stage is declared to have type `range` but is used as type `pl.process.stage.Stage`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "examples/process_error.py",
    "min_patch_found": false,
    "full_warning_msg": "examples/process_error.py:17:26 Incompatible parameter type [6]: Expected `pl.process.stage.Stage` for 2nd positional only parameter to call `pl.process.api.map` but got `range`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:45:4 Incompatible variable type [9]: iterable is declared to have type `typing.Iterable[typing.Any]` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:46:4 Incompatible variable type [9]: maxsize is declared to have type `int` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:65:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:67:26 Incompatible parameter type [6]: Expected `int` for 2nd parameter `maxsize` to call `from_iterable` but got `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:118:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:122:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:123:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:160:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:202:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:206:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:207:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:260:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:302:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:306:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:307:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:344:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:384:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:388:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:389:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:433:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:461:8 Incompatible return type [7]: Expected `Stage` but got implicit return value of `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:535:12 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:571:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:632:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/process/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/process/api.py:646:8 Incompatible return type [7]: Expected `typing.Iterable[typing.Any]` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:39:4 Incompatible variable type [9]: iterable is declared to have type `typing.Iterable[typing.Any]` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:40:4 Incompatible variable type [9]: maxsize is declared to have type `int` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:41:4 Incompatible variable type [9]: worker_constructor is declared to have type `typing.Type[typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:56:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:58:26 Incompatible parameter type [6]: Expected `int` for 2nd parameter `maxsize` to call `from_iterable` but got `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:106:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:107:4 Incompatible variable type [9]: workers is declared to have type `int` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:108:4 Incompatible variable type [9]: maxsize is declared to have type `int` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:110:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:111:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:148:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:183:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:187:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:188:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:242:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:277:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:281:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:282:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:319:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:355:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:359:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:360:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:407:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:429:8 Incompatible return type [7]: Expected `Stage` but got implicit return value of `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:492:12 Incompatible return type [7]: Expected `None` but got `typing.Generator[typing.Any, None, None]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:495:12 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:533:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:588:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/sync/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/sync/api.py:602:8 Incompatible return type [7]: Expected `typing.Iterable[typing.Any]` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:112:4 Incompatible variable type [9]: iterable is declared to have type `typing.Iterable[typing.Any]` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:113:4 Incompatible variable type [9]: maxsize is declared to have type `int` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:132:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:133:53 Incompatible parameter type [6]: Expected `int` for 2nd parameter `maxsize` to call `from_iterable` but got `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:185:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:189:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:190:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:227:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:287:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:291:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:292:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:345:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:391:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:395:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:396:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:433:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:476:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:480:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:481:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:525:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:553:8 Incompatible return type [7]: Expected `Stage` but got implicit return value of `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:627:12 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:663:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:724:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/task/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/task/api.py:738:8 Incompatible return type [7]: Expected `typing.Iterable[typing.Any]` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/task/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:44:4 Incompatible variable type [9]: iterable is declared to have type `typing.Iterable[typing.Any]` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:45:4 Incompatible variable type [9]: maxsize is declared to have type `int` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:65:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:67:26 Incompatible parameter type [6]: Expected `int` for 2nd parameter `maxsize` to call `from_iterable` but got `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:118:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:122:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:123:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:163:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:205:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:209:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:210:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:266:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:308:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:312:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:313:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:353:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:393:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:397:4 Incompatible variable type [9]: on_start is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:398:4 Incompatible variable type [9]: on_done is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:445:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:473:8 Incompatible return type [7]: Expected `Stage` but got implicit return value of `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:549:12 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:585:8 Incompatible return type [7]: Expected `Stage` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:646:4 Incompatible variable type [9]: stage is declared to have type `Stage` but is used as type `pypeln_utils.Undefined`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "pypeln/thread/api.py",
    "min_patch_found": false,
    "full_warning_msg": "pypeln/thread/api.py:660:8 Incompatible return type [7]: Expected `typing.Iterable[typing.Any]` but got `pypeln_utils.Partial`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/thread/api.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "tests/test_process.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/process/api/map_process_test.py",
    "file_hunks_size": 11,
    "min_patch_found": true,
    "single_hunk": true,
    "fit_TFix": false,
    "delete_only_patch": true,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "tests/test_process.py:419:40 Incompatible parameter type [6]: Expected `pl.process.stage.Stage` for 2nd positional only parameter to call `pl.process.api.map` but got `range`.",
    "message": " Expected `pl.process.stage.Stage` for 2nd positional only parameter to call `pl.process.api.map` but got `range`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 419,
    "warning_line": "    stage = pl.process.map(raise_error, range(10))",
    "min_patch": [
      {
        "hunk_fit_TFix": false,
        "inside_window": true,
        "delete_only": true,
        "has_suppression": false,
        "source_code": "    assert isinstance(error, MyError)\n\n\n###################\n# from_to_iterable\n###################\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_from_to_iterable(nums):\n\n    nums_pl = nums\n    nums_pl = pl.process.from_iterable(nums_pl)\n    nums_pl = cz.partition_all(10, nums_pl)\n    nums_pl = pl.process.map(sum, nums_pl)\n    nums_pl = list(nums_pl)\n\n    nums_py = nums\n    nums_py = cz.partition_all(10, nums_py)\n    nums_py = map(sum, nums_py)\n    nums_py = list(nums_py)\n\n    assert nums_py == nums_pl\n\n\nif __name__ == \"__main__\":\n    error = None\n\n    def raise_error(x):\n        raise MyError()\n\n    stage = pl.process.map(raise_error, range(10))\n\n    list(stage)\n",
        "source_code_len": 714,
        "target_code": "    assert isinstance(error, MyError)\n",
        "target_code_len": 38,
        "diff_format": "@@ -389,33 +185,1 @@\n     assert isinstance(error, MyError)\n-\n-\n-###################\n-# from_to_iterable\n-###################\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_from_to_iterable(nums):\n-\n-    nums_pl = nums\n-    nums_pl = pl.process.from_iterable(nums_pl)\n-    nums_pl = cz.partition_all(10, nums_pl)\n-    nums_pl = pl.process.map(sum, nums_pl)\n-    nums_pl = list(nums_pl)\n-\n-    nums_py = nums\n-    nums_py = cz.partition_all(10, nums_py)\n-    nums_py = map(sum, nums_py)\n-    nums_py = list(nums_py)\n-\n-    assert nums_py == nums_pl\n-\n-\n-if __name__ == \"__main__\":\n-    error = None\n-\n-    def raise_error(x):\n-        raise MyError()\n-\n-    stage = pl.process.map(raise_error, range(10))\n-\n-    list(stage)\n",
        "source_code_with_indent": "    <DED>assert isinstance(error, MyError)\n\n\n###################\n# from_to_iterable\n###################\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_from_to_iterable(nums):\n\n    <IND>nums_pl = nums\n    nums_pl = pl.process.from_iterable(nums_pl)\n    nums_pl = cz.partition_all(10, nums_pl)\n    nums_pl = pl.process.map(sum, nums_pl)\n    nums_pl = list(nums_pl)\n\n    nums_py = nums\n    nums_py = cz.partition_all(10, nums_py)\n    nums_py = map(sum, nums_py)\n    nums_py = list(nums_py)\n\n    assert nums_py == nums_pl\n\n\n<DED>if __name__ == \"__main__\":\n    <IND>error = None\n\n    def raise_error(x):\n        <IND>raise MyError()\n\n    <DED>stage = pl.process.map(raise_error, range(10))\n\n    list(stage)\n",
        "source_code_with_indent_exact_match": true,
        "target_code_with_indent": "    <DED>assert isinstance(error, MyError)\n",
        "target_code_with_indent_exact_match": true
      }
    ]
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "tests/test_sync.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/pypeln/sync/api/map_sync_test.py",
    "file_hunks_size": 3,
    "min_patch_found": true,
    "single_hunk": true,
    "fit_TFix": false,
    "delete_only_patch": true,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "tests/test_sync.py:419:37 Incompatible parameter type [6]: Expected `pl.sync.stage.Stage` for 2nd positional only parameter to call `pl.sync.api.map` but got `range`.",
    "message": " Expected `pl.sync.stage.Stage` for 2nd positional only parameter to call `pl.sync.api.map` but got `range`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 419,
    "warning_line": "    stage = pl.sync.map(raise_error, range(10))",
    "min_patch": [
      {
        "hunk_fit_TFix": false,
        "inside_window": true,
        "delete_only": true,
        "has_suppression": false,
        "source_code": "\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_map_square_workers_sorted(nums):\n\n    nums_py = map(lambda x: x ** 2, nums)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums, workers=2)\n    nums_pl = pl.sync.ordered(nums_pl)\n    nums_pl = list(nums_pl)\n\n    assert nums_pl == nums_py\n\n\n############\n# each\n############\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_each(nums):\n\n    nums_pl = pl.sync.each(lambda x: x, nums)\n    pl.sync.run(nums_pl)\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_each_list(nums):\n\n    nums_pl = pl.sync.each(lambda x: x, nums)\n    nums_pl = list(nums_pl)\n\n    assert nums_pl == []\n\n\n############\n# flat_map\n############\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square(nums):\n    def _generator(x):\n        yield x\n        yield x + 1\n        yield x + 2\n\n    nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n    nums_pl = pl.sync.flat_map(_generator, nums_pl)\n    nums_pl = list(nums_pl)\n\n    assert nums_pl == nums_py\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square_workers(nums):\n    def _generator(x):\n        yield x\n        yield x + 1\n        yield x + 2\n\n    nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n    nums_pl = pl.sync.flat_map(_generator, nums_pl, workers=3)\n    nums_pl = list(nums_pl)\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n############\n# filter\n############\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square_filter_workers(nums):\n    def _generator(x):\n        yield x\n        yield x + 1\n        yield x + 2\n\n    nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = cz.filter(lambda x: x > 1, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n    nums_pl = pl.sync.flat_map(_generator, nums_pl, workers=3)\n    nums_pl = pl.sync.filter(lambda x: x > 1, nums_pl)\n    nums_pl = list(nums_pl)\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square_filter_workers_pipe(nums):\n    def _generator(x):\n        yield x\n        yield x + 1\n        yield x + 2\n\n    nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = cz.filter(lambda x: x > 1, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = (\n        nums\n        | pl.sync.map(lambda x: x ** 2)\n        | pl.sync.flat_map(_generator, workers=3)\n        | pl.sync.filter(lambda x: x > 1)\n        | list\n    )\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n############\n# concat\n############\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_concat_basic(nums):\n\n    nums_py = list(map(lambda x: x + 1, nums))\n    nums_py1 = list(map(lambda x: x ** 2, nums_py))\n    nums_py2 = list(map(lambda x: -x, nums_py))\n    nums_py = nums_py1 + nums_py2\n\n    nums_pl = pl.sync.map(lambda x: x + 1, nums)\n    nums_pl1 = pl.sync.map(lambda x: x ** 2, nums_pl)\n    nums_pl2 = pl.sync.map(lambda x: -x, nums_pl)\n    nums_pl = pl.sync.concat([nums_pl1, nums_pl2])\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_concat_multiple(nums):\n\n    nums_py = [x + 1 for x in nums]\n    nums_py1 = nums_py + nums_py\n    nums_py2 = nums_py1 + nums_py\n\n    nums_pl = pl.sync.map(lambda x: x + 1, nums)\n    nums_pl1 = pl.sync.concat([nums_pl, nums_pl])\n    nums_pl2 = pl.sync.concat([nums_pl1, nums_pl])\n\n    assert sorted(nums_py2) == sorted(list(nums_pl2))\n\n\n###################\n# error handling\n###################\n\n\nclass MyError(Exception):\n    pass\n\n\ndef test_error_handling():\n\n    error = None\n\n    def raise_error(x):\n        raise MyError()\n\n    stage = pl.sync.map(raise_error, range(10))\n\n    try:\n        list(stage)\n\n    except MyError as e:\n        error = e\n    except BaseException as e:\n        error = e\n        print(e)\n\n    assert isinstance(error, MyError)\n\n\n###################\n# from_to_iterable\n###################\n@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_from_to_iterable(nums):\n\n    nums_pl = nums\n    nums_pl = pl.sync.from_iterable(nums_pl)\n    nums_pl = cz.partition_all(10, nums_pl)\n    nums_pl = pl.sync.map(sum, nums_pl)\n    nums_pl = list(nums_pl)\n\n    nums_py = nums\n    nums_py = cz.partition_all(10, nums_py)\n    nums_py = map(sum, nums_py)\n    nums_py = list(nums_py)\n\n    assert nums_py == nums_pl\n\n\nif __name__ == \"__main__\":\n    error = None\n\n    def raise_error(x):\n        raise MyError()\n\n    stage = pl.sync.map(raise_error, range(10))\n\n    list(stage)\n",
        "source_code_len": 5146,
        "target_code": "\n\n    assert nums_pl == nums_py\n",
        "target_code_len": 32,
        "diff_format": "@@ -194,228 +159,3 @@\n \n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_map_square_workers_sorted(nums):\n-\n-    nums_py = map(lambda x: x ** 2, nums)\n-    nums_py = list(nums_py)\n-\n-    nums_pl = pl.sync.map(lambda x: x ** 2, nums, workers=2)\n-    nums_pl = pl.sync.ordered(nums_pl)\n-    nums_pl = list(nums_pl)\n \n     assert nums_pl == nums_py\n-\n-\n-############\n-# each\n-############\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_each(nums):\n-\n-    nums_pl = pl.sync.each(lambda x: x, nums)\n-    pl.sync.run(nums_pl)\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_each_list(nums):\n-\n-    nums_pl = pl.sync.each(lambda x: x, nums)\n-    nums_pl = list(nums_pl)\n-\n-    assert nums_pl == []\n-\n-\n-############\n-# flat_map\n-############\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_flat_map_square(nums):\n-    def _generator(x):\n-        yield x\n-        yield x + 1\n-        yield x + 2\n-\n-    nums_py = map(lambda x: x ** 2, nums)\n-    nums_py = cz.mapcat(_generator, nums_py)\n-    nums_py = list(nums_py)\n-\n-    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n-    nums_pl = pl.sync.flat_map(_generator, nums_pl)\n-    nums_pl = list(nums_pl)\n-\n-    assert nums_pl == nums_py\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_flat_map_square_workers(nums):\n-    def _generator(x):\n-        yield x\n-        yield x + 1\n-        yield x + 2\n-\n-    nums_py = map(lambda x: x ** 2, nums)\n-    nums_py = cz.mapcat(_generator, nums_py)\n-    nums_py = list(nums_py)\n-\n-    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n-    nums_pl = pl.sync.flat_map(_generator, nums_pl, workers=3)\n-    nums_pl = list(nums_pl)\n-\n-    assert sorted(nums_pl) == sorted(nums_py)\n-\n-\n-############\n-# filter\n-############\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_flat_map_square_filter_workers(nums):\n-    def _generator(x):\n-        yield x\n-        yield x + 1\n-        yield x + 2\n-\n-    nums_py = map(lambda x: x ** 2, nums)\n-    nums_py = cz.mapcat(_generator, nums_py)\n-    nums_py = cz.filter(lambda x: x > 1, nums_py)\n-    nums_py = list(nums_py)\n-\n-    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n-    nums_pl = pl.sync.flat_map(_generator, nums_pl, workers=3)\n-    nums_pl = pl.sync.filter(lambda x: x > 1, nums_pl)\n-    nums_pl = list(nums_pl)\n-\n-    assert sorted(nums_pl) == sorted(nums_py)\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_flat_map_square_filter_workers_pipe(nums):\n-    def _generator(x):\n-        yield x\n-        yield x + 1\n-        yield x + 2\n-\n-    nums_py = map(lambda x: x ** 2, nums)\n-    nums_py = cz.mapcat(_generator, nums_py)\n-    nums_py = cz.filter(lambda x: x > 1, nums_py)\n-    nums_py = list(nums_py)\n-\n-    nums_pl = (\n-        nums\n-        | pl.sync.map(lambda x: x ** 2)\n-        | pl.sync.flat_map(_generator, workers=3)\n-        | pl.sync.filter(lambda x: x > 1)\n-        | list\n-    )\n-\n-    assert sorted(nums_pl) == sorted(nums_py)\n-\n-\n-############\n-# concat\n-############\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_concat_basic(nums):\n-\n-    nums_py = list(map(lambda x: x + 1, nums))\n-    nums_py1 = list(map(lambda x: x ** 2, nums_py))\n-    nums_py2 = list(map(lambda x: -x, nums_py))\n-    nums_py = nums_py1 + nums_py2\n-\n-    nums_pl = pl.sync.map(lambda x: x + 1, nums)\n-    nums_pl1 = pl.sync.map(lambda x: x ** 2, nums_pl)\n-    nums_pl2 = pl.sync.map(lambda x: -x, nums_pl)\n-    nums_pl = pl.sync.concat([nums_pl1, nums_pl2])\n-\n-    assert sorted(nums_pl) == sorted(nums_py)\n-\n-\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_concat_multiple(nums):\n-\n-    nums_py = [x + 1 for x in nums]\n-    nums_py1 = nums_py + nums_py\n-    nums_py2 = nums_py1 + nums_py\n-\n-    nums_pl = pl.sync.map(lambda x: x + 1, nums)\n-    nums_pl1 = pl.sync.concat([nums_pl, nums_pl])\n-    nums_pl2 = pl.sync.concat([nums_pl1, nums_pl])\n-\n-    assert sorted(nums_py2) == sorted(list(nums_pl2))\n-\n-\n-###################\n-# error handling\n-###################\n-\n-\n-class MyError(Exception):\n-    pass\n-\n-\n-def test_error_handling():\n-\n-    error = None\n-\n-    def raise_error(x):\n-        raise MyError()\n-\n-    stage = pl.sync.map(raise_error, range(10))\n-\n-    try:\n-        list(stage)\n-\n-    except MyError as e:\n-        error = e\n-    except BaseException as e:\n-        error = e\n-        print(e)\n-\n-    assert isinstance(error, MyError)\n-\n-\n-###################\n-# from_to_iterable\n-###################\n-@hp.given(nums=st.lists(st.integers()))\n-@hp.settings(max_examples=MAX_EXAMPLES)\n-def test_from_to_iterable(nums):\n-\n-    nums_pl = nums\n-    nums_pl = pl.sync.from_iterable(nums_pl)\n-    nums_pl = cz.partition_all(10, nums_pl)\n-    nums_pl = pl.sync.map(sum, nums_pl)\n-    nums_pl = list(nums_pl)\n-\n-    nums_py = nums\n-    nums_py = cz.partition_all(10, nums_py)\n-    nums_py = map(sum, nums_py)\n-    nums_py = list(nums_py)\n-\n-    assert nums_py == nums_pl\n-\n-\n-if __name__ == \"__main__\":\n-    error = None\n-\n-    def raise_error(x):\n-        raise MyError()\n-\n-    stage = pl.sync.map(raise_error, range(10))\n-\n-    list(stage)\n",
        "source_code_with_indent": "\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_map_square_workers_sorted(nums):\n\n    <IND>nums_py = map(lambda x: x ** 2, nums)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums, workers=2)\n    nums_pl = pl.sync.ordered(nums_pl)\n    nums_pl = list(nums_pl)\n\n    assert nums_pl == nums_py\n\n\n############\n# each\n############\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_each(nums):\n\n    <IND>nums_pl = pl.sync.each(lambda x: x, nums)\n    pl.sync.run(nums_pl)\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_each_list(nums):\n\n    <IND>nums_pl = pl.sync.each(lambda x: x, nums)\n    nums_pl = list(nums_pl)\n\n    assert nums_pl == []\n\n\n############\n# flat_map\n############\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square(nums):\n    <IND>def _generator(x):\n        <IND>yield x\n        yield x + 1\n        yield x + 2\n\n    <DED>nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n    nums_pl = pl.sync.flat_map(_generator, nums_pl)\n    nums_pl = list(nums_pl)\n\n    assert nums_pl == nums_py\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square_workers(nums):\n    <IND>def _generator(x):\n        <IND>yield x\n        yield x + 1\n        yield x + 2\n\n    <DED>nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n    nums_pl = pl.sync.flat_map(_generator, nums_pl, workers=3)\n    nums_pl = list(nums_pl)\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n############\n# filter\n############\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square_filter_workers(nums):\n    <IND>def _generator(x):\n        <IND>yield x\n        yield x + 1\n        yield x + 2\n\n    <DED>nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = cz.filter(lambda x: x > 1, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = pl.sync.map(lambda x: x ** 2, nums)\n    nums_pl = pl.sync.flat_map(_generator, nums_pl, workers=3)\n    nums_pl = pl.sync.filter(lambda x: x > 1, nums_pl)\n    nums_pl = list(nums_pl)\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_flat_map_square_filter_workers_pipe(nums):\n    <IND>def _generator(x):\n        <IND>yield x\n        yield x + 1\n        yield x + 2\n\n    <DED>nums_py = map(lambda x: x ** 2, nums)\n    nums_py = cz.mapcat(_generator, nums_py)\n    nums_py = cz.filter(lambda x: x > 1, nums_py)\n    nums_py = list(nums_py)\n\n    nums_pl = (\n        nums\n        | pl.sync.map(lambda x: x ** 2)\n        | pl.sync.flat_map(_generator, workers=3)\n        | pl.sync.filter(lambda x: x > 1)\n        | list\n    )\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n############\n# concat\n############\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_concat_basic(nums):\n\n    <IND>nums_py = list(map(lambda x: x + 1, nums))\n    nums_py1 = list(map(lambda x: x ** 2, nums_py))\n    nums_py2 = list(map(lambda x: -x, nums_py))\n    nums_py = nums_py1 + nums_py2\n\n    nums_pl = pl.sync.map(lambda x: x + 1, nums)\n    nums_pl1 = pl.sync.map(lambda x: x ** 2, nums_pl)\n    nums_pl2 = pl.sync.map(lambda x: -x, nums_pl)\n    nums_pl = pl.sync.concat([nums_pl1, nums_pl2])\n\n    assert sorted(nums_pl) == sorted(nums_py)\n\n\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_concat_multiple(nums):\n\n    <IND>nums_py = [x + 1 for x in nums]\n    nums_py1 = nums_py + nums_py\n    nums_py2 = nums_py1 + nums_py\n\n    nums_pl = pl.sync.map(lambda x: x + 1, nums)\n    nums_pl1 = pl.sync.concat([nums_pl, nums_pl])\n    nums_pl2 = pl.sync.concat([nums_pl1, nums_pl])\n\n    assert sorted(nums_py2) == sorted(list(nums_pl2))\n\n\n###################\n# error handling\n###################\n\n\n<DED>class MyError(Exception):\n    <IND>pass\n\n\n<DED>def test_error_handling():\n\n    <IND>error = None\n\n    def raise_error(x):\n        <IND>raise MyError()\n\n    <DED>stage = pl.sync.map(raise_error, range(10))\n\n    try:\n        <IND>list(stage)\n\n    <DED>except MyError as e:\n        <IND>error = e\n    <DED>except BaseException as e:\n        <IND>error = e\n        print(e)\n\n    <DED>assert isinstance(error, MyError)\n\n\n###################\n# from_to_iterable\n###################\n<DED>@hp.given(nums=st.lists(st.integers()))\n@hp.settings(max_examples=MAX_EXAMPLES)\ndef test_from_to_iterable(nums):\n\n    <IND>nums_pl = nums\n    nums_pl = pl.sync.from_iterable(nums_pl)\n    nums_pl = cz.partition_all(10, nums_pl)\n    nums_pl = pl.sync.map(sum, nums_pl)\n    nums_pl = list(nums_pl)\n\n    nums_py = nums\n    nums_py = cz.partition_all(10, nums_py)\n    nums_py = map(sum, nums_py)\n    nums_py = list(nums_py)\n\n    assert nums_py == nums_pl\n\n\n<DED>if __name__ == \"__main__\":\n    <IND>error = None\n\n    def raise_error(x):\n        <IND>raise MyError()\n\n    <DED>stage = pl.sync.map(raise_error, range(10))\n\n    list(stage)\n",
        "source_code_with_indent_exact_match": true,
        "target_code_with_indent": "\n\n    assert nums_pl == nums_py\n",
        "target_code_with_indent_exact_match": true
      }
    ]
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "tests/test_task.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/test_task.py:527:37 Incompatible parameter type [6]: Expected `pl.task.stage.Stage` for 2nd positional only parameter to call `pl.task.api.map` but got `range`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/tests/test_task.py'",
    "dd_fail": true
  },
  {
    "project": "cgarciae/pypeln",
    "commit": "142a9f20c2765b8c751a853b27cace83a275dd01",
    "filename": "tests/test_thread.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/test_thread.py:421:39 Incompatible parameter type [6]: Expected `pl.thread.stage.Stage` for 2nd positional only parameter to call `pl.thread.api.map` but got `range`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgarciae-pypeln/tests/test_thread.py'",
    "dd_fail": true
  }
]