[
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/assets/topology.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/assets/topology.py",
    "file_hunks_size": 15,
    "min_patch_found": true,
    "single_hunk": true,
    "fit_TFix": true,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/assets/topology.py:361:15 Invalid type [31]: Expression `nptyping.Array[(int, ..., 2)]` is not a valid type.",
    "message": " Expression `nptyping.Array[(int, ..., 2)]` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 361,
    "warning_line": "        edges: Array[int, ..., 2],",
    "min_patch": [
      {
        "hunk_fit_TFix": true,
        "inside_window": true,
        "delete_only": false,
        "has_suppression": false,
        "source_code": "        unconf_lith_id: int,\n        edges: Array[int, ..., 2],\n        centroids: Dict[int, np.ndarray]\n",
        "source_code_len": 105,
        "target_code": "        unconf_lith_id: int,\n        edges: np.ndarray,\n        centroids: Dict[int, np.ndarray]\n",
        "target_code_len": 97,
        "diff_format": "@@ -360,3 +358,3 @@\n         unconf_lith_id: int,\n-        edges: Array[int, ..., 2],\n+        edges: np.ndarray,\n         centroids: Dict[int, np.ndarray]\n",
        "source_code_with_indent": "        unconf_lith_id: int,\n        edges: Array[int, ..., 2],\n        centroids: Dict[int, np.ndarray]\n",
        "source_code_with_indent_exact_match": true,
        "target_code_with_indent": "        unconf_lith_id: int,\n        edges: np.ndarray,\n        centroids: Dict[int, np.ndarray]\n",
        "target_code_with_indent_exact_match": true
      }
    ]
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:360:43 Incompatible variable type [9]: offset_faults is declared to have type `bool` but is used as type `None`.",
    "message": " offset_faults is declared to have type `bool` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 360,
    "warning_line": "    def set_default_faults_relations(self, offset_faults:bool=None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:458:31 Incompatible variable type [9]: series_names is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " series_names is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 458,
    "warning_line": "    def __init__(self, faults, series_names: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:860:24 Incompatible variable type [9]: id_list is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " id_list is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 860,
    "warning_line": "    def update_id(self, id_list: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:1424:59 Incompatible variable type [9]: surface is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " surface is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 1424,
    "warning_line": "    def set_surface_points(self, coord: np.ndarray = None, surface: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:1596:28 Incompatible variable type [9]: kwargs_pandas is declared to have type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "message": " kwargs_pandas is declared to have type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 1596,
    "warning_line": "                            kwargs_pandas: dict = None, **kwargs, ):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:1711:57 Incompatible variable type [9]: surface is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " surface is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 1711,
    "warning_line": "                         orientation: np.ndarray = None, surface: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:1993:70 Incompatible variable type [9]: kwargs_pandas is declared to have type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "message": " kwargs_pandas is declared to have type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 1993,
    "warning_line": "    def read_orientations(self, file_path, debug=False, inplace=True, kwargs_pandas: dict = None, **kwargs):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:2182:17 Incompatible variable type [9]: rescaling_factor is declared to have type `float` but is used as type `None`.",
    "message": " rescaling_factor is declared to have type `float` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 2182,
    "warning_line": "                 rescaling_factor: float = None, centers: Union[list, pn.DataFrame] = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:2366:74 Incompatible variable type [9]: idx is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " idx is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 2366,
    "warning_line": "    def rescale_surface_points(surface_points, rescaling_factor, centers, idx: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:2423:70 Incompatible variable type [9]: idx is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " idx is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 2423,
    "warning_line": "    def rescale_orientations(orientations, rescaling_factor, centers, idx: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/data.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/data.py",
    "file_hunks_size": 58,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/core/data.py:2876:26 Incompatible variable type [9]: u_grade is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " u_grade is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 2876,
    "warning_line": "    def set_u_grade(self, u_grade: list = None):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/gempy_api.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/gempy_api.py:135:39 Incompatible variable type [9]: output is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/gempy_api.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/gempy_api.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/gempy_api.py:136:44 Incompatible variable type [9]: verbose is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/gempy_api.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/gempy_api.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/gempy_api.py:328:8 Incompatible return type [7]: Expected `Solution` but got implicit return value of `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/core/gempy_api.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/model.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/model.py:369:27 Incompatible variable type [9]: series_fault is declared to have type `Union[typing.List[typing.Any], str]` but is used as type `None`.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/model.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/model.py:506:56 Incompatible parameter type [6]: Expected `typing.List[typing.Any]` for 2nd positional only parameter to call `Surfaces.add_surfaces_values` but got `Union[typing.List[typing.Any], str]`.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/model.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/model.py:884:33 Incompatible variable type [9]: rename_series is declared to have type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/core/model.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/core/model.py:1315:56 Incompatible variable type [9]: verbose is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/plot.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/plot/plot.py:358:19 Invalid type [31]: Expression `typing.Dict[(int, nptyping.Array[(int, 3)])]` is not a valid type.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/plot.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/plot/plot.py:361:8 Incompatible variable type [9]: label_kwargs is declared to have type `Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/plot.py",
    "min_patch_found": false,
    "full_warning_msg": "gempy/plot/plot.py:362:8 Incompatible variable type [9]: edge_kwargs is declared to have type `Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "'bool' object has no attribute 'items'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:445:12 Incompatible variable type [9]: extent is declared to have type `List[float]` but is used as type `None`.",
    "message": " extent is declared to have type `List[float]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 445,
    "warning_line": "            extent: List[float] = None,"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:525:34 Incompatible variable type [9]: fmt is declared to have type `str` but is used as type `None`.",
    "message": " fmt is declared to have type `str` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 525,
    "warning_line": "    def plot_surface_points(self, fmt: str = None, **kwargs):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:547:32 Incompatible variable type [9]: fmt is declared to have type `str` but is used as type `None`.",
    "message": " fmt is declared to have type `str` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 547,
    "warning_line": "    def plot_orientations(self, fmt: str = None, length: float = None, **kwargs):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:547:49 Incompatible variable type [9]: length is declared to have type `float` but is used as type `None`.",
    "message": " length is declared to have type `float` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 547,
    "warning_line": "    def plot_orientations(self, fmt: str = None, length: float = None, **kwargs):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:639:12 Incompatible variable type [9]: value is declared to have type `float` but is used as type `None`.",
    "message": " value is declared to have type `float` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 639,
    "warning_line": "            value: float = None"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:686:32 Incompatible variable type [9]: fmts is declared to have type `Iterable[str]` but is used as type `None`.",
    "message": " fmts is declared to have type `Iterable[str]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 686,
    "warning_line": "    def plot_surfaces_all(self, fmts: Iterable[str] = None, **kwargs):"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:704:44 Invalid type [31]: Expression `nptyping.Array[(int, ..., 3)]` is not a valid type.",
    "message": " Expression `nptyping.Array[(int, ..., 3)]` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 704,
    "warning_line": "    def _simplices_to_pv_tri_simplices(sim: Array[int, ..., 3]) -> Array["
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:704:67 Invalid type [31]: Expression `nptyping.Array[(int, ..., 4)]` is not a valid type.",
    "message": " Expression `nptyping.Array[(int, ..., 4)]` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 704,
    "warning_line": "    def _simplices_to_pv_tri_simplices(sim: Array[int, ..., 3]) -> Array["
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:711:46 Incompatible variable type [9]: series is declared to have type `str` but is used as type `None`.",
    "message": " series is declared to have type `str` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 711,
    "warning_line": "    def plot_structured_grid(self, name: str, series: str = None, render_topography: bool = False,"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/vista.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/vista.py",
    "file_hunks_size": 26,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/vista.py:743:16 Incompatible return type [7]: Expected `List[typing.Any]` but got `None`.",
    "message": " Expected `List[typing.Any]` but got `None`.",
    "rule_id": "Incompatible return type [7]",
    "warning_line_no": 743,
    "warning_line": "                return"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "gempy/plot/visualization_2d.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/gempy/plot/visualization_2d.py",
    "file_hunks_size": 11,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "gempy/plot/visualization_2d.py:489:23 Incompatible variable type [9]: solution is declared to have type `Solution` but is used as type `None`.",
    "message": " solution is declared to have type `Solution` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 489,
    "warning_line": "    def plot_map(self, solution: Solution = None, contour_lines=False, show_data=True,"
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:142:9 Invalid type [31]: Expression `nptyping.Array[(int, 3, ...)]` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:185:26 Invalid type [31]: Expression `nptyping.Array[(int, 3, ..., ..., ...)]` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:238:24 Invalid type [31]: Expression `nptyping.Array[(int, 3, ...)]` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:374:12 Incompatible parameter type [6]: Expected `typing.Sized` for 1st positional only parameter to call `len` but got `Iterable[typing.Any]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:392:38 Invalid type [31]: Expression `nptyping.Array[(int, ..., 2)]` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:412:42 Invalid type [31]: Expression `nptyping.Array[(int, ..., 2)]` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  },
  {
    "project": "cgre-aachen/gempy",
    "commit": "a0a4e5bdf417fd13741fd5b29916845f93dc2098",
    "filename": "notebooks/experimental/topology/topology_numpy.py",
    "min_patch_found": false,
    "full_warning_msg": "notebooks/experimental/topology/topology_numpy.py:428:31 Incompatible parameter type [6]: Expected `Iterable[Variable[_T]]` for 1st positional only parameter to call `sum` but got `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/cgre-aachen-gempy/notebooks/experimental/topology/topology_numpy.py'",
    "dd_fail": true
  }
]