[
  {
    "project": "althonos/pronto",
    "commit": "a8f731a63d12ef3eb6a59425ce8e77579942027d",
    "filename": "pronto/term.py",
    "min_patch_found": false,
    "full_warning_msg": "pronto/term.py:254:41 Incompatible parameter type [6]: Expected `int` for 2nd parameter `distance` to call `pronto.logic.lineage.LineageHandler.__init__` but got `Optional[int]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "althonos/pronto",
    "commit": "a8f731a63d12ef3eb6a59425ce8e77579942027d",
    "filename": "pronto/term.py",
    "min_patch_found": false,
    "full_warning_msg": "pronto/term.py:300:39 Incompatible parameter type [6]: Expected `int` for 2nd parameter `distance` to call `pronto.logic.lineage.LineageHandler.__init__` but got `Optional[int]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]