[
  {
    "project": "asyml/forte",
    "commit": "d2bcaa9dcb5d369675fb21330e59921d73c9667d",
    "filename": "tests/forte/data/container_test.py",
    "min_patch_found": false,
    "full_warning_msg": "tests/forte/data/container_test.py:39:4 Inconsistent override [14]: `tests.forte.data.container_test.DummyContainer.get_entry` overrides method defined in `EntryContainer` inconsistently. Could not find parameter `ptr` in overriding signature.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/asyml-forte/tests/forte/data/container_test.py'",
    "dd_fail": true
  },
  {
    "project": "asyml/forte",
    "commit": "d2bcaa9dcb5d369675fb21330e59921d73c9667d",
    "filename": "tests/forte/processors/allennlp_processors_test.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/asyml-forte/tests/forte/processors/allennlp_processors_test.py",
    "file_hunks_size": 4,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "tests/forte/processors/allennlp_processors_test.py:229:24 Unbound name [10]: Name `PredicateMention` is used but not defined in the current scope.",
    "message": " Name `PredicateMention` is used but not defined in the current scope.",
    "rule_id": "Unbound name [10]",
    "warning_line_no": 229,
    "warning_line": "                parent: PredicateMention = srl_links[index].get_parent()"
  },
  {
    "project": "asyml/forte",
    "commit": "d2bcaa9dcb5d369675fb21330e59921d73c9667d",
    "filename": "tests/forte/processors/allennlp_processors_test.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/asyml-forte/tests/forte/processors/allennlp_processors_test.py",
    "file_hunks_size": 4,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "tests/forte/processors/allennlp_processors_test.py:230:23 Unbound name [10]: Name `PredicateArgument` is used but not defined in the current scope.",
    "message": " Name `PredicateArgument` is used but not defined in the current scope.",
    "rule_id": "Unbound name [10]",
    "warning_line_no": 230,
    "warning_line": "                child: PredicateArgument = srl_links[index].get_child()"
  }
]