[
  {
    "project": "googleapis/python-bigquery",
    "commit": "cbcb4b86d2d01fb983c20271958b11665e8f7d03",
    "filename": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py",
    "min_patch_found": false,
    "full_warning_msg": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py:6:5 Unsupported operand [58]: `<` is not supported for operand types `typing.Union[int, str]` and `int`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/googleapis-python-bigquery/google/cloud/bigquery_v2/proto/location_metadata_pb2.py'",
    "dd_fail": true
  },
  {
    "project": "googleapis/python-bigquery",
    "commit": "cbcb4b86d2d01fb983c20271958b11665e8f7d03",
    "filename": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py",
    "min_patch_found": false,
    "full_warning_msg": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py:24:23 Call error [29]: `typing.Union[typing.Callable[[Named(x, typing.Any)], typing.Any], bool]` is not a function.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/googleapis-python-bigquery/google/cloud/bigquery_v2/proto/location_metadata_pb2.py'",
    "dd_fail": true
  },
  {
    "project": "googleapis/python-bigquery",
    "commit": "cbcb4b86d2d01fb983c20271958b11665e8f7d03",
    "filename": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py",
    "min_patch_found": false,
    "full_warning_msg": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py:27:18 Call error [29]: `typing.Union[typing.Callable[[Named(x, typing.Any)], typing.Any], bool]` is not a function.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/googleapis-python-bigquery/google/cloud/bigquery_v2/proto/location_metadata_pb2.py'",
    "dd_fail": true
  },
  {
    "project": "googleapis/python-bigquery",
    "commit": "cbcb4b86d2d01fb983c20271958b11665e8f7d03",
    "filename": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py",
    "min_patch_found": false,
    "full_warning_msg": "google/cloud/bigquery_v2/proto/location_metadata_pb2.py:50:26 Call error [29]: `typing.Union[typing.Callable[[Named(x, typing.Any)], typing.Any], bool]` is not a function.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/googleapis-python-bigquery/google/cloud/bigquery_v2/proto/location_metadata_pb2.py'",
    "dd_fail": true
  }
]