[
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "0f7a90d6551743b9099685989b7d8490bf55c2dd",
    "filename": "aries_cloudagent/resolver/did_resolver.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/resolver/did_resolver.py:64:8 Incompatible return type [7]: Expected `Sequence[BaseDIDResolver]` but got `typing.List[str]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]