[
  {
    "project": "QCoDeS/Qcodes",
    "commit": "dc94b4d6ffe483767f9abdf38eb7f6906e7b8631",
    "filename": "qcodes/dataset/measurements.py",
    "min_patch_found": false,
    "full_warning_msg": "qcodes/dataset/measurements.py:571:12 Incompatible parameter type [6]: Expected `Sequence[Dict[typing.Any, typing.Any]]` for 5th parameter `parent_datasets` to call `DataSetProtocol.prepare` but got `Sequence[Mapping[typing.Any, typing.Any]]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "QCoDeS/Qcodes",
    "commit": "dc94b4d6ffe483767f9abdf38eb7f6906e7b8631",
    "filename": "qcodes/utils/dataset/doNd.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/QCoDeS-Qcodes/qcodes/utils/dataset/doNd.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "qcodes/utils/dataset/doNd.py:232:28 Incompatible parameter type [6]: Expected `DataSet` for 1st positional only parameter to call `_handle_plotting` but got `qcodes.dataset.data_set_protocol.DataSetProtocol`.",
    "message": " Expected `DataSet` for 1st positional only parameter to call `_handle_plotting` but got `qcodes.dataset.data_set_protocol.DataSetProtocol`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 232,
    "warning_line": "    return _handle_plotting(dataset, do_plot)"
  },
  {
    "project": "QCoDeS/Qcodes",
    "commit": "dc94b4d6ffe483767f9abdf38eb7f6906e7b8631",
    "filename": "qcodes/utils/dataset/doNd.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/QCoDeS-Qcodes/qcodes/utils/dataset/doNd.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "qcodes/utils/dataset/doNd.py:343:28 Incompatible parameter type [6]: Expected `DataSet` for 1st positional only parameter to call `_handle_plotting` but got `qcodes.dataset.data_set_protocol.DataSetProtocol`.",
    "message": " Expected `DataSet` for 1st positional only parameter to call `_handle_plotting` but got `qcodes.dataset.data_set_protocol.DataSetProtocol`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 343,
    "warning_line": "    return _handle_plotting(dataset, do_plot, interrupted())"
  },
  {
    "project": "QCoDeS/Qcodes",
    "commit": "dc94b4d6ffe483767f9abdf38eb7f6906e7b8631",
    "filename": "qcodes/utils/dataset/doNd.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/QCoDeS-Qcodes/qcodes/utils/dataset/doNd.py",
    "file_hunks_size": 5,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "qcodes/utils/dataset/doNd.py:495:28 Incompatible parameter type [6]: Expected `DataSet` for 1st positional only parameter to call `_handle_plotting` but got `qcodes.dataset.data_set_protocol.DataSetProtocol`.",
    "message": " Expected `DataSet` for 1st positional only parameter to call `_handle_plotting` but got `qcodes.dataset.data_set_protocol.DataSetProtocol`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 495,
    "warning_line": "    return _handle_plotting(dataset, do_plot, interrupted())"
  }
]