[
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:37:4 Incompatible attribute type [8]: Attribute `cos_function` declared in class `Model` has type `pydantic.types.PyObject` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:39:4 Incompatible attribute type [8]: Attribute `path_to_something` declared in class `Model` has type `Path` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:40:4 Incompatible attribute type [8]: Attribute `path_to_file` declared in class `Model` has type `pydantic.types.FilePath` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:41:4 Incompatible attribute type [8]: Attribute `path_to_directory` declared in class `Model` has type `pydantic.types.DirectoryPath` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:43:17 Invalid type [31]: Expression `pydantic.conbytes($parameter$min_length = 2, $parameter$max_length = 10)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:44:17 Invalid type [31]: Expression `pydantic.conbytes($parameter$strip_whitespace = True)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:46:15 Invalid type [31]: Expression `pydantic.constr($parameter$min_length = 2, $parameter$max_length = 10)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:47:15 Invalid type [31]: Expression `pydantic.constr($parameter$regex = \"apple (pie|tart|sandwich)\")` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:48:15 Invalid type [31]: Expression `pydantic.constr($parameter$strip_whitespace = True)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:50:13 Invalid type [31]: Expression `pydantic.conint($parameter$gt = 1000, $parameter$lt = 1024)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:51:13 Invalid type [31]: Expression `pydantic.conint($parameter$multiple_of = 5)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:52:4 Incompatible attribute type [8]: Attribute `pos_int` declared in class `Model` has type `pydantic.types.PositiveInt` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:53:4 Incompatible attribute type [8]: Attribute `neg_int` declared in class `Model` has type `pydantic.types.NegativeInt` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:55:15 Invalid type [31]: Expression `pydantic.confloat($parameter$gt = 1000, $parameter$lt = 1024)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:56:19 Invalid type [31]: Expression `pydantic.confloat($parameter$ge = 0, $parameter$le = 1)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:57:15 Invalid type [31]: Expression `pydantic.confloat($parameter$multiple_of = 0.500000)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:58:4 Incompatible attribute type [8]: Attribute `pos_float` declared in class `Model` has type `pydantic.types.PositiveFloat` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:59:4 Incompatible attribute type [8]: Attribute `neg_float` declared in class `Model` has type `pydantic.types.NegativeFloat` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:61:16 Invalid type [31]: Expression `pydantic.conlist(int, $parameter$min_items = 1, $parameter$max_items = 4)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:63:4 Incompatible attribute type [8]: Attribute `email_address` declared in class `Model` has type `pydantic.networks.EmailStr` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:64:4 Incompatible attribute type [8]: Attribute `email_and_name` declared in class `Model` has type `pydantic.networks.NameEmail` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:66:4 Incompatible attribute type [8]: Attribute `password` declared in class `Model` has type `pydantic.types.SecretStr` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:67:4 Incompatible attribute type [8]: Attribute `password_bytes` declared in class `Model` has type `pydantic.types.SecretBytes` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:69:4 Incompatible attribute type [8]: Attribute `decimal` declared in class `Model` has type `Decimal` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:70:22 Invalid type [31]: Expression `pydantic.condecimal($parameter$gt = 0)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:71:22 Invalid type [31]: Expression `pydantic.condecimal($parameter$lt = 0)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:72:35 Invalid type [31]: Expression `pydantic.condecimal($parameter$max_digits = 2, $parameter$decimal_places = 2)` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:73:17 Invalid type [31]: Expression `pydantic.condecimal($parameter$multiple_of = decimal.Decimal(\"0.25\"))` is not a valid type.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:74:4 Incompatible attribute type [8]: Attribute `uuid_any` declared in class `Model` has type `UUID` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:75:4 Incompatible attribute type [8]: Attribute `uuid_v1` declared in class `Model` has type `pydantic.types.UUID1` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:76:4 Incompatible attribute type [8]: Attribute `uuid_v3` declared in class `Model` has type `pydantic.types.UUID3` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:77:4 Incompatible attribute type [8]: Attribute `uuid_v4` declared in class `Model` has type `pydantic.types.UUID4` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:78:4 Incompatible attribute type [8]: Attribute `uuid_v5` declared in class `Model` has type `pydantic.types.UUID5` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:79:4 Incompatible attribute type [8]: Attribute `ipvany` declared in class `Model` has type `pydantic.networks.IPvAnyAddress` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:80:4 Incompatible attribute type [8]: Attribute `ipv4` declared in class `Model` has type `IPv4Address` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:81:4 Incompatible attribute type [8]: Attribute `ipv6` declared in class `Model` has type `IPv6Address` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:82:4 Incompatible attribute type [8]: Attribute `ip_vany_network` declared in class `Model` has type `pydantic.networks.IPvAnyNetwork` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:83:4 Incompatible attribute type [8]: Attribute `ip_v4_network` declared in class `Model` has type `IPv4Network` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:84:4 Incompatible attribute type [8]: Attribute `ip_v6_network` declared in class `Model` has type `IPv6Network` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:85:4 Incompatible attribute type [8]: Attribute `ip_vany_interface` declared in class `Model` has type `pydantic.networks.IPvAnyInterface` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:86:4 Incompatible attribute type [8]: Attribute `ip_v4_interface` declared in class `Model` has type `IPv4Interface` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "33b7d52d31ca0a5f5bd3193b54678b8a68d6737c",
    "filename": "docs/examples/exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/examples/exotic.py:87:4 Incompatible attribute type [8]: Attribute `ip_v6_interface` declared in class `Model` has type `IPv6Interface` but is used as type `None`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/samuelcolvin-pydantic/docs/examples/exotic.py'",
    "dd_fail": true
  }
]