[
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/classifier.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/classifier.py",
    "file_hunks_size": 10,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/classifier.py:18:17 Incompatible variable type [9]: threshold is declared to have type `float` but is used as type `None`.",
    "message": " threshold is declared to have type `float` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 18,
    "warning_line": "                 threshold: float = None,"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/classifier.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/classifier.py",
    "file_hunks_size": 10,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/classifier.py:112:25 Call error [29]: `Optional[typing.Callable[[Variable(typing.Any), Keywords(typing.Any)], typing.Any]]` is not a function.",
    "message": " `Optional[typing.Callable[[Variable(typing.Any), Keywords(typing.Any)], typing.Any]]` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 112,
    "warning_line": "            self.X_ref = self.preprocess_fn(X_ref)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/classifier.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/classifier.py",
    "file_hunks_size": 10,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/classifier.py:230:61 Incompatible parameter type [6]: Expected `Dict[str, int]` for 4th positional only parameter to call `update_reference` but got `Optional[Dict[str, int]]`.",
    "message": " Expected `Dict[str, int]` for 4th positional only parameter to call `update_reference` but got `Optional[Dict[str, int]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 230,
    "warning_line": "        self.X_ref = update_reference(self.X_ref, X, self.n, self.update_X_ref)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/mmd.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/mmd.py",
    "file_hunks_size": 7,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/mmd.py:195:61 Incompatible parameter type [6]: Expected `Dict[str, int]` for 4th positional only parameter to call `update_reference` but got `Optional[Dict[str, int]]`.",
    "message": " Expected `Dict[str, int]` for 4th positional only parameter to call `update_reference` but got `Optional[Dict[str, int]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 195,
    "warning_line": "        self.X_ref = update_reference(self.X_ref, X, self.n, self.update_X_ref)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/preprocess.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/preprocess.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/preprocess.py:17:17 Incompatible variable type [9]: Unable to unpack `None`, expected a tuple.",
    "message": " Unable to unpack `None`, expected a tuple.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 17,
    "warning_line": "                 shape: tuple = None,"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/preprocess.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/preprocess.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/preprocess.py:18:17 Incompatible variable type [9]: enc_dim is declared to have type `int` but is used as type `None`.",
    "message": " enc_dim is declared to have type `int` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 18,
    "warning_line": "                 enc_dim: int = None"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/preprocess.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/preprocess.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/preprocess.py:49:17 Incompatible variable type [9]: Unable to unpack `None`, expected a tuple.",
    "message": " Unable to unpack `None`, expected a tuple.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 49,
    "warning_line": "                 input_shape: tuple = None"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/cd/preprocess.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/cd/preprocess.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/cd/preprocess.py:66:21 Incompatible variable type [9]: max_len is declared to have type `int` but is used as type `None`.",
    "message": " max_len is declared to have type `int` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 66,
    "warning_line": "                     max_len: int = None,"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:63:12 Call error [29]: `Sampling` is not a function.",
    "message": " `Sampling` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 63,
    "warning_line": "        z = self.sampling((z_mean, z_log_var))"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:120:31 Call error [29]: `EncoderVAE` is not a function.",
    "message": " `EncoderVAE` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 120,
    "warning_line": "        z_mean, z_log_var, z = self.encoder(x)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:121:18 Call error [29]: `Decoder` is not a function.",
    "message": " `Decoder` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 121,
    "warning_line": "        x_recon = self.decoder(z)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:173:12 Call error [29]: `EncoderAE` is not a function.",
    "message": " `EncoderAE` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 173,
    "warning_line": "        z = self.encoder(x)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:174:18 Call error [29]: `Decoder` is not a function.",
    "message": " `Decoder` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 174,
    "warning_line": "        x_recon = self.decoder(z)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:208:17 Incompatible variable type [9]: output_activation is declared to have type `str` but is used as type `None`.",
    "message": " output_activation is declared to have type `str` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 208,
    "warning_line": "                 output_activation: str = None,"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:275:21 Call error [29]: `EncoderLSTM` is not a function.",
    "message": " `EncoderLSTM` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 275,
    "warning_line": "        init_state = self.encoder(x)[1]"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:276:24 Call error [29]: `DecoderLSTM` is not a function.",
    "message": " `DecoderLSTM` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 276,
    "warning_line": "        x_recon, z, _ = self.decoder(x, init_state=init_state)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:296:21 Call error [29]: `EncoderLSTM` is not a function.",
    "message": " `EncoderLSTM` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 296,
    "warning_line": "        init_state = self.encoder(x)[1]"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:310:29 Call error [29]: `DecoderLSTM` is not a function.",
    "message": " `DecoderLSTM` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 310,
    "warning_line": "            decoder_output = self.decoder(decoder_input, init_state=init_state)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/autoencoder.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/autoencoder.py:447:37 Call error [29]: `EncoderVAE` is not a function.",
    "message": " `EncoderVAE` is not a function.",
    "rule_id": "Call error [29]",
    "warning_line_no": 447,
    "warning_line": "        enc_mean, enc_log_var, enc = self.encoder(x)"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/embedding.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/embedding.py",
    "file_hunks_size": 4,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/embedding.py:40:17 Incompatible variable type [9]: layers is declared to have type `List[int]` but is used as type `None`.",
    "message": " layers is declared to have type `List[int]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 40,
    "warning_line": "                 layers: List[int] = None"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/losses.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/losses.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/losses.py:35:8 Incompatible variable type [9]: sim is declared to have type `float` but is used as type `None`.",
    "message": " sim is declared to have type `float` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 35,
    "warning_line": "        sim = None"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/losses.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/losses.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/losses.py:135:16 Incompatible variable type [9]: model_hl is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " model_hl is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 135,
    "warning_line": "                model_hl: list = None,"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/losses.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/losses.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/losses.py:138:16 Incompatible variable type [9]: w_model_hl is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "message": " w_model_hl is declared to have type `typing.List[typing.Any]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 138,
    "warning_line": "                w_model_hl: list = None,"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/pixelcnn.py",
    "min_patch_found": false,
    "full_warning_msg": "alibi_detect/models/pixelcnn.py:218:17 Incompatible variable type [9]: Unable to unpack `None`, expected a tuple.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/tests/test_autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/tests/test_autoencoder_tf.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/tests/test_autoencoder.py:97:45 Incompatible parameter type [6]: Expected `str` for 3rd positional only parameter to call `DecoderLSTM.__init__` but got `None`.",
    "message": " Expected `str` for 3rd positional only parameter to call `DecoderLSTM.__init__` but got `None`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 97,
    "warning_line": "tests_seq2seq = [(DecoderLSTM(latent_dim, 1, None), 1),"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/tests/test_autoencoder.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/models/tensorflow/tests/test_autoencoder_tf.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "alibi_detect/models/tests/test_autoencoder.py:98:45 Incompatible parameter type [6]: Expected `str` for 3rd positional only parameter to call `DecoderLSTM.__init__` but got `None`.",
    "message": " Expected `str` for 3rd positional only parameter to call `DecoderLSTM.__init__` but got `None`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 98,
    "warning_line": "                 (DecoderLSTM(latent_dim, 2, None), 2)]"
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/trainer.py",
    "min_patch_found": false,
    "full_warning_msg": "alibi_detect/models/trainer.py:11:12 Incompatible variable type [9]: loss_fn_kwargs is declared to have type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/models/trainer.py",
    "min_patch_found": false,
    "full_warning_msg": "alibi_detect/models/trainer.py:12:12 Incompatible variable type [9]: preprocess_fn is declared to have type `typing.Callable[..., typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "SeldonIO/alibi-detect",
    "commit": "386bb8d8fec1ccadd1a7c25de1c68cd45fd24280",
    "filename": "alibi_detect/utils/kernels.py",
    "min_patch_found": false,
    "full_warning_msg": "alibi_detect/utils/kernels.py:32:8 Unsupported operand [58]: `@` is not supported for operand types `float` and `typing.Any`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/SeldonIO-alibi-detect/alibi_detect/utils/kernels.py'",
    "dd_fail": true
  }
]