[
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype/vale/_factory/_valeiscls.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype/vale/_is/_valeiscls.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype/vale/_factory/_valeiscls.py:210:55 Incompatible parameter type [6]: Expected `typing.Union[typing.Type[typing.Any], typing.Tuple[typing.Type[typing.Any], ...]]` for 2nd positional only parameter to call `is_type_subclass` but got `typing.Union[tuple[typing.Type[typing.Any]], typing.Type[typing.Any]]`.",
    "message": " Expected `typing.Union[typing.Type[typing.Any], typing.Tuple[typing.Type[typing.Any], ...]]` for 2nd positional only parameter to call `is_type_subclass` but got `typing.Union[tuple[typing.Type[typing.Any]], typing.Type[typing.Any]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 210,
    "warning_line": "        is_valid = lambda pith: is_type_subclass(pith, base_classes)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:116:11 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Tuple[]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Tuple[]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 116,
    "warning_line": "        Is[()]"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:121:8 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Tuple[str, str]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Tuple[str, str]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 121,
    "warning_line": "        Is['Cannon to right of them,', 'Cannon to left of them,']"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:126:11 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `str`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `str`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 126,
    "warning_line": "        Is['Cannon in front of them']"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:136:11 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Callable[[], bool]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Callable[[], bool]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 136,
    "warning_line": "        Is[lambda: True]"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:141:11 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Callable[[], bool]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 1st positional only parameter to call `beartype.vale._factory._valeis._IsFactory.__getitem__` but got `typing.Callable[[], bool]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 141,
    "warning_line": "        Is[lambda: True]"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:151:21 Unsupported operand [58]: `&` is not supported for operand types `BeartypeValidator` and `str`.",
    "message": " `&` is not supported for operand types `BeartypeValidator` and `str`.",
    "rule_id": "Unsupported operand [58]",
    "warning_line_no": 151,
    "warning_line": "        IsNonEmpty & 'While horse and hero fell.'"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:153:21 Unsupported operand [58]: `|` is not supported for operand types `BeartypeValidator` and `str`.",
    "message": " `|` is not supported for operand types `BeartypeValidator` and `str`.",
    "rule_id": "Unsupported operand [58]",
    "warning_line_no": 153,
    "warning_line": "        IsNonEmpty | 'While horse and hero fell.'"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_is/test_valeis.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/_factory/test_valeis.py:190:43 Invalid type [31]: Expression `$local_beartype_test?a00_unit?a20_api?vale?_factory?test_valeis?test_api_vale_decor_fail$Annotated[(str, beartype.vale.Is[lambda ($parameter$text) (bool(\"Flashed as they turned in air\"))], \"Sabring the gunners there,\")]` is not a valid type.",
    "message": " Expression `$local_beartype_test?a00_unit?a20_api?vale?_factory?test_valeis?test_api_vale_decor_fail$Annotated[(str, beartype.vale.Is[lambda ($parameter$text) (bool(\"Flashed as they turned in air\"))], \"Sabring the gunners there,\")]` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 190,
    "warning_line": "            flashed_all_their_sabres_bare: Annotated["
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:41:25 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]` for 2nd positional only parameter to call `dict.__setitem__` but got `typing.Callable[[], str]`.",
    "message": " Expected `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]` for 2nd positional only parameter to call `dict.__setitem__` but got `typing.Callable[[], str]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 41,
    "warning_line": "    kwargs['get_repr'] = lambda: ("
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:52:49 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 52,
    "warning_line": "        is_valid_code=is_valid_code_delimited, **kwargs)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:52:49 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 52,
    "warning_line": "        is_valid_code=is_valid_code_delimited, **kwargs)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:52:49 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[], str], str]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Union[typing.Callable[[], str], str]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 52,
    "warning_line": "        is_valid_code=is_valid_code_delimited, **kwargs)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:57:51 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 57,
    "warning_line": "        is_valid_code=is_valid_code_undelimited, **kwargs)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:57:51 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 57,
    "warning_line": "        is_valid_code=is_valid_code_undelimited, **kwargs)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:57:51 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[], str], str]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Union[typing.Callable[[], str], str]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 57,
    "warning_line": "        is_valid_code=is_valid_code_undelimited, **kwargs)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:67:10 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 3rd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 3rd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 67,
    "warning_line": "        **kwargs_sans_get_repr"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:67:10 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 3rd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 3rd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 67,
    "warning_line": "        **kwargs_sans_get_repr"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:95:12 Incompatible parameter type [6]: Expected `str` for 2nd parameter `is_valid_code` to call `BeartypeValidator.__init__` but got `bytes`.",
    "message": " Expected `str` for 2nd parameter `is_valid_code` to call `BeartypeValidator.__init__` but got `bytes`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 95,
    "warning_line": "            is_valid_code=b'Into the jaws of Death,',"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:127:12 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 3rd parameter `is_valid_code_locals` to call `BeartypeValidator.__init__` but got `typing.Set[typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 3rd parameter `is_valid_code_locals` to call `BeartypeValidator.__init__` but got `typing.Set[typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 127,
    "warning_line": "            is_valid_code_locals={'yum', into_the_jaws_of_death},"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:142:26 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[], str], str]` for 1st parameter `get_repr` to call `BeartypeValidator.__init__` but got `bytes`.",
    "message": " Expected `typing.Union[typing.Callable[[], str], str]` for 1st parameter `get_repr` to call `BeartypeValidator.__init__` but got `bytes`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 142,
    "warning_line": "        BeartypeValidator(get_repr=b'All that was left of them,', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:142:68 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 142,
    "warning_line": "        BeartypeValidator(get_repr=b'All that was left of them,', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:142:68 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 142,
    "warning_line": "        BeartypeValidator(get_repr=b'All that was left of them,', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:142:68 Incompatible parameter type [6]: Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 142,
    "warning_line": "        BeartypeValidator(get_repr=b'All that was left of them,', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:148:41 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 148,
    "warning_line": "        BeartypeValidator(get_repr='', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:148:41 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 148,
    "warning_line": "        BeartypeValidator(get_repr='', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:148:41 Incompatible parameter type [6]: Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 148,
    "warning_line": "        BeartypeValidator(get_repr='', **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:154:43 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 154,
    "warning_line": "        BeartypeValidator(get_repr=iter, **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:154:43 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 154,
    "warning_line": "        BeartypeValidator(get_repr=iter, **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:154:43 Incompatible parameter type [6]: Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 154,
    "warning_line": "        BeartypeValidator(get_repr=iter, **kwargs_good)"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:161:12 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[], str], str]` for 1st parameter `get_repr` to call `BeartypeValidator.__init__` but got `typing.Callable[[Named(rode, typing.Any), Named(the, typing.Any), Named(six, typing.Any), Named(hundred, typing.Any)], str]`.",
    "message": " Expected `typing.Union[typing.Callable[[], str], str]` for 1st parameter `get_repr` to call `BeartypeValidator.__init__` but got `typing.Callable[[Named(rode, typing.Any), Named(the, typing.Any), Named(six, typing.Any), Named(hundred, typing.Any)], str]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 161,
    "warning_line": "            get_repr=lambda rode, the, six, hundred:"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:163:14 Incompatible parameter type [6]: Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Callable[[typing.Any], bool]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 163,
    "warning_line": "            **kwargs_good"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:163:14 Incompatible parameter type [6]: Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `typing.Dict[str, typing.Any]` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 163,
    "warning_line": "            **kwargs_good"
  },
  {
    "project": "beartype/beartype",
    "commit": "2b5165ce13ad7a74e60eba59223bb8fc1c1aa474",
    "filename": "beartype_test/a00_unit/a20_api/vale/test_valevale.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/beartype-beartype/beartype_test/a00_unit/a20_api/vale/_core/test_valecore.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "beartype_test/a00_unit/a20_api/vale/test_valevale.py:163:14 Incompatible parameter type [6]: Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "message": " Expected `str` for 2nd positional only parameter to call `BeartypeValidator.__init__` but got `typing.Union[typing.Callable[[Named(text, typing.Any)], bool], str, typing.Dict[str, typing.Callable[[Named(text, typing.Any)], bool]]]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 163,
    "warning_line": "            **kwargs_good"
  }
]