[
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/core/data/dataset.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/deepmipt-DeepPavlov/deeppavlov/core/data/dataset_iterator.py",
    "file_hunks_size": 4,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "deeppavlov/core/data/dataset.py:29:17 Incompatible variable type [9]: seed is declared to have type `int` but is used as type `None`.",
    "message": " seed is declared to have type `int` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 29,
    "warning_line": "                 seed: int = None, shuffle: bool = True,"
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/core/data/dataset.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/deepmipt-DeepPavlov/deeppavlov/core/data/dataset_iterator.py",
    "file_hunks_size": 4,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "deeppavlov/core/data/dataset.py:58:24 Incompatible variable type [9]: shuffle is declared to have type `bool` but is used as type `None`.",
    "message": " shuffle is declared to have type `bool` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 58,
    "warning_line": "                        shuffle: bool = None) -> Generator:"
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/dataset_readers/basic_ner_dataset_reader.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/deepmipt-DeepPavlov/deeppavlov/dataset_readers/conll2003_reader.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "deeppavlov/dataset_readers/basic_ner_dataset_reader.py:15:4 Inconsistent override [14]: `deeppavlov.dataset_readers.basic_ner_dataset_reader.NerDatasetReader.read` overrides method defined in `DatasetReader` inconsistently. Could not find parameter `file_path` in overriding signature.",
    "message": " `deeppavlov.dataset_readers.basic_ner_dataset_reader.NerDatasetReader.read` overrides method defined in `DatasetReader` inconsistently. Could not find parameter `file_path` in overriding signature.",
    "rule_id": "Inconsistent override [14]",
    "warning_line_no": 15,
    "warning_line": "    def read(self, dir_path: str, dataset_name='conll2003'):"
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/dataset_readers/basic_ner_dataset_reader.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/deepmipt-DeepPavlov/deeppavlov/dataset_readers/conll2003_reader.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "deeppavlov/dataset_readers/basic_ner_dataset_reader.py:16:8 Incompatible variable type [9]: dir_path is declared to have type `str` but is used as type `Path`.",
    "message": " dir_path is declared to have type `str` but is used as type `Path`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 16,
    "warning_line": "        dir_path = Path(dir_path)"
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/dataset_readers/typos.py",
    "min_patch_found": false,
    "full_warning_msg": "deeppavlov/dataset_readers/typos.py:57:8 Incompatible variable type [9]: data_path is declared to have type `str` but is used as type `Path`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/dataset_readers/typos.py",
    "min_patch_found": false,
    "full_warning_msg": "deeppavlov/dataset_readers/typos.py:59:16 Unsupported operand [58]: `/` is not supported for operand types `str` and `str`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/dataset_readers/typos.py",
    "min_patch_found": false,
    "full_warning_msg": "deeppavlov/dataset_readers/typos.py:94:8 Incompatible variable type [9]: data_path is declared to have type `str` but is used as type `Path`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/dataset_readers/typos.py",
    "min_patch_found": false,
    "full_warning_msg": "deeppavlov/dataset_readers/typos.py:96:16 Unsupported operand [58]: `/` is not supported for operand types `str` and `str`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/datasets/classification_dataset.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/deepmipt-DeepPavlov/deeppavlov/dataset_iterators/basic_classification_iterator.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "deeppavlov/datasets/classification_dataset.py:37:17 Incompatible variable type [9]: seed is declared to have type `int` but is used as type `None`.",
    "message": " seed is declared to have type `int` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 37,
    "warning_line": "                 seed: int = None, shuffle: bool = True,"
  },
  {
    "project": "deepmipt/DeepPavlov",
    "commit": "d1bccd145b90f1e19386d262f2366fd131ffdf4f",
    "filename": "deeppavlov/datasets/intent_dataset.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/deepmipt-DeepPavlov/deeppavlov/dataset_iterators/dstc2_intents_iterator.py",
    "file_hunks_size": 2,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "deeppavlov/datasets/intent_dataset.py:38:17 Incompatible variable type [9]: seed is declared to have type `int` but is used as type `None`.",
    "message": " seed is declared to have type `int` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 38,
    "warning_line": "                 seed: int = None, shuffle: bool = True,"
  }
]