[
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/example1.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/example1.py:8:4 Incompatible attribute type [8]: Attribute `signup_ts` declared in class `User` has type `datetime` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/example2.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/example2.py:3:4 Unbound name [10]: Name `User` is used but not defined in the current scope.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_errors.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_errors.py:11:4 Incompatible attribute type [8]: Attribute `list_of_ints` declared in class `Model` has type `List[int]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_errors.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_errors.py:12:4 Incompatible attribute type [8]: Attribute `a_float` declared in class `Model` has type `float` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_errors.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_errors.py:14:4 Incompatible attribute type [8]: Attribute `recursive_model` declared in class `Model` has type `Location` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:7:4 Incompatible attribute type [8]: Attribute `cos_function` declared in class `Model` has type `pydantic.types.PyObject` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:8:4 Incompatible attribute type [8]: Attribute `path_to_something` declared in class `Model` has type `Path` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:10:15 Invalid type [31]: Expression `pydantic.constr($parameter$min_length = 2, $parameter$max_length = 10)` is not a valid type.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:11:15 Invalid type [31]: Expression `pydantic.constr($parameter$regex = \"apple (pie|tart|sandwich)\")` is not a valid type.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:13:13 Invalid type [31]: Expression `pydantic.conint($parameter$gt = 1000, $parameter$lt = 1024)` is not a valid type.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:14:4 Incompatible attribute type [8]: Attribute `pos_int` declared in class `Model` has type `pydantic.types.PositiveInt` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:15:4 Incompatible attribute type [8]: Attribute `neg_int` declared in class `Model` has type `pydantic.types.NegativeInt` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:17:4 Incompatible attribute type [8]: Attribute `email_address` declared in class `Model` has type `pydantic.types.EmailStr` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:18:4 Incompatible attribute type [8]: Attribute `email_and_name` declared in class `Model` has type `pydantic.types.NameEmail` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:22:4 Incompatible attribute type [8]: Attribute `db_password` declared in class `Model` has type `str` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:26:4 Incompatible attribute type [8]: Attribute `db_query` declared in class `Model` has type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_exotic.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_exotic.py:27:4 Incompatible attribute type [8]: Attribute `dsn` declared in class `Model` has type `pydantic.types.DSN` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_recursive.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_recursive.py:6:4 Incompatible attribute type [8]: Attribute `size` declared in class `Foo` has type `float` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_settings.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_settings.py:8:4 Incompatible attribute type [8]: Attribute `redis_password` declared in class `Settings` has type `str` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_settings.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_settings.py:12:4 Incompatible attribute type [8]: Attribute `invoicing_cls` declared in class `Settings` has type `pydantic.types.PyObject` but is used as type `str`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_settings.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_settings.py:16:4 Incompatible attribute type [8]: Attribute `db_password` declared in class `Settings` has type `str` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_settings.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_settings.py:20:4 Incompatible attribute type [8]: Attribute `db_query` declared in class `Settings` has type `typing.Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_settings.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_settings.py:21:4 Incompatible attribute type [8]: Attribute `dsn` declared in class `Settings` has type `pydantic.types.DSN` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:7:4 Incompatible attribute type [8]: Attribute `simple_list` declared in class `Model` has type `List[typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:8:4 Incompatible attribute type [8]: Attribute `list_of_ints` declared in class `Model` has type `List[int]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:10:4 Incompatible attribute type [8]: Attribute `simple_dict` declared in class `Model` has type `Dict[typing.Any, typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:11:4 Incompatible attribute type [8]: Attribute `dict_str_float` declared in class `Model` has type `Dict[str, float]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:13:4 Incompatible attribute type [8]: Attribute `simple_set` declared in class `Model` has type `Set[typing.Any]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:14:4 Incompatible attribute type [8]: Attribute `set_bytes` declared in class `Model` has type `Set[bytes]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:16:4 Incompatible attribute type [8]: Attribute `str_or_bytes` declared in class `Model` has type `Union[bytes, str]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "samuelcolvin/pydantic",
    "commit": "c81ec9aeecad3555596865aa648058f394bcedeb",
    "filename": "docs/usage_typing.py",
    "min_patch_found": false,
    "full_warning_msg": "docs/usage_typing.py:19:4 Incompatible attribute type [8]: Attribute `compound` declared in class `Model` has type `Dict[Union[bytes, str], List[Set[int]]]` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]